print("Lets play Silly Sentences!")
name = input("Enter a name:")
place = input("Enter a place:")
adjective1 = input("Enter an adjective:")
adjective2 = input("Enter an adjective:")
food1 = input("Enter a food:")
food2 = input("Enter another food:")
adverb = input("Enter an adverb:")
verb = input("Enter a verb:")
noun = input("Enter a noun:")
print(name + " was planning a dream vacation to " + place + ". " )
print(name + " was especially looking forward to trying the local cuisine, including " + adjective1 + " " + food1 + " and, " + food2 + ".")
print(name + " will have to practice the language " + adverb + " to make it easier to " + verb + " with people.")
print(name + " has a long list of sights to see, including the " + noun + " museum and the " + adjective2 + " park.")